openapi: 3.0.0
info:
  version: '1.1.2'
  title: wingnut-api
  description: The API for Wingnut IoT
paths:
  /users:
    get:
      summary: Get a list of account user IDs
      description: Get a list of account user IDs
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      responses:
        '200':
          $ref: '#/components/responses/UsersFetched'
        '403':
          $ref: '#/components/responses/Forbidden'
    post:
      summary: Query users
      description: Query detail for users
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        $ref: '#/components/requestBodies/QueryEntities'
      responses:
        '200':
          $ref: '#/components/responses/UsersQueried'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
  /wingnuts:
    get:
      summary: Get a list of account wingnut device IDs
      description: Get a list of account wingnut device IDs
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      responses:
        '200':
          $ref: '#/components/responses/WingnutsFetched'
        '403':
          $ref: '#/components/responses/Forbidden'
    post:
      summary: Query wingnut devices
      description: Query detail for wingnut devices
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        $ref: '#/components/requestBodies/QueryEntities'
      responses:
        '200':
          $ref: '#/components/responses/WingnutsQueried'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
  /properties:
    get:
      summary: Get a list of account property IDs
      description: Get a list of account property IDs
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      responses:
        '200':
          $ref: '#/components/responses/PropertiesFetched'
        '403':
          $ref: '#/components/responses/Forbidden'
    post:
      summary: Query properties
      description: Query detail for properties
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        $ref: '#/components/requestBodies/QueryEntities'
      responses:
        '200':
          $ref: '#/components/responses/PropertiesQueried'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
  /properties/records:
    post:
      summary: Query historical property records for a single property
      description: Records from any time are available through this endpoint but only for a single property.
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        $ref: '#/components/requestBodies/QueryPropertyRecords'
      responses:
        '200':
          $ref: '#/components/responses/PropertyRecordsQueried'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /properties/records_last_24h:
    post:
      summary: Query recent (last 24 hours) property records for multiple properties.
      description: Records for multiple properties can be queried at once thorugh this endpoint but only for records within the last 24 hours.
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        $ref: '#/components/requestBodies/QueryPropertyRecords24H'
      responses:
        '200':
          $ref: '#/components/responses/PropertyRecordsQueried'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  schemas:
    Label:
      type: string
      example: 'SystemPumpCurrent1'
      description: Label/descriptor of the sensor's data
    Data:
      type: object
      properties:
        label:
          $ref: '#/components/schemas/Label'
        value:
          anyOf:
            - type: boolean
            - type: number
              format: float
    Record:
      type: object
      properties:
        propertyId:
          type: string
          format: uuid
          example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
          description: Static UUID-4 for property
        propertyName:
          type: string
          example: 'Happy Apartments'
          description: User customizable name for property
        propertyExternalId:
          type: string
          example: '00123-A'
          description: User customizable ID for property
        timestamp:
          type: string
          format: timestamp
          example: '2024-08-17T15:29:15'
          description: The time by which to stop querying records for in format yyyy-MM-ddTHH:mm:ss
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data'
    Address:
      type: object
      properties:
        city:
          type: string
          example: 'Calgary'
          description: The city in whichthe property is located
        country:
          type: string
          example: 'Canada'
          description: The country in which the property is located
        postalZip:
          type: string
          example: 'A1A 2B2'
          description: The postal or zip code for the property
        provinceState:
          type: string
          example: 'Alberta'
          description: The proince or state in which the property is located
        streetAddress:
          type: string
          example: '123 Happy Street NW'
          description: The street address of the property
          properties:
            id:
              type: string
              format: uuid
              example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
              description: The user ID of the recipient. Querable via /users endpoint
            type:
              type: string
              example: 'email'
              description: The notification method/s for the recipient. Currently only supports email
    Alarms:
      type: object
      properties:
        boilerSystemPressure1:
          type: string
          example: 'OK'
          description: A sensors alarm state for boiler system pressure 1
        boilerReturnHeaderTemperature1:
          type: string
          example: 'OK'
          description: A sensors alarm state for boiler return header temperature 1
      description: Label and alarm state objects, varies depending on what sensors and alarms exist
    Sensor:
      type: object
      properties:
        label:
          $ref: '#/components/schemas/Label'
        type:
          type: string
          example: 'thermistor4334K'
          description: The type of sensor
    Property:
      type: object
      properties:
        entityType:
          type: string
          example: 'property'
          description: The type of the entity
        entityStatus:
          type: string
          example: "active"
          description: The status of the property entity
        externalId:
          type: string
          example: '00123-A'
          description: User customizable ID for property
        companyName:
          type: string
          example: 'Bruces Corp.'
          description: The name of the company that the property belongs to
        createdAt:
          type: string
          example: '2022-09-13 15:55:16'
          description: The timestamp of when the property entity was created
        id:
          type: string
          format: uuid
          example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
          description: Static UUID-4 for property
        config:
          type: object
          properties:
            companyId:
              type: string
              example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
              description: The company Id the property belongs to              
            name:
              type: string
              example: 'Happy Apartments'
              description: User customizable name for property
            portfolio:
              type: string
              example: 'A1'
              description: User customizable portfolio name/ID for property
            address:
              $ref: '#/components/schemas/Address'
            alarmState:
              type: string
              example: 'ALARM'
              description: Identifies if any alarms are active at the property
            alarms:
              $ref: '#/components/schemas/Alarms'
    Wingnut:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
          description: Static UUID-4 for wingnut
        entityType:
          type: string
          format: string
          example: 'wingnut'
          description: Entity type
        externalId:
          type: string
          format: string
          example: '100'
          description: Optional user supplied name
        entityStatus:
          type: string
          example: 'live'
          description: The wingnuts status (live, linked, unlinked, unassigned)
        companyName:
          type: string
          example: 'Example Inc'
          description: The company the wingnut is registered to
        propertyName:
          type: string
          example: 'Bruces House'
          description: The name of the property that the wignut device is linked to
        createdAt:
          type: string
          example: '2022-04-05 14:41:51'
          description: The timestamp of when the wingnut object was created
        config:
          type: object
          properties:
            companyId:
              type: string
              example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
              description: The company Id the wingnut is registered to
            propertyId:
              type: string
              example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
              description: The property Id the wingnut is registered to
            latestPost:
              type: string
              example: '2024-10-30 17:36:25'
              description: The timestamp of the latest wingnut post
            latestPostIp:
              type: string
              example: '96.51.48.35'
              description: The ip address of the latest wingnut post
            sensors:
              type: object
              properties:
                AN1:
                  $ref: '#/components/schemas/Sensor'
                AN2:
                  $ref: '#/components/schemas/Sensor'
                AN3:
                  $ref: '#/components/schemas/Sensor'
                AN4:
                  $ref: '#/components/schemas/Sensor'
                AN5:
                  $ref: '#/components/schemas/Sensor'
                AN6:
                  $ref: '#/components/schemas/Sensor'
                AN7:
                  $ref: '#/components/schemas/Sensor'
                AN8:
                  $ref: '#/components/schemas/Sensor'
                AN9:
                  $ref: '#/components/schemas/Sensor'
                AN10:
                  $ref: '#/components/schemas/Sensor'
                AN11:
                  $ref: '#/components/schemas/Sensor'
                AN12:
                  $ref: '#/components/schemas/Sensor'
                AN13:
                  $ref: '#/components/schemas/Sensor'
                AN14:
                  $ref: '#/components/schemas/Sensor'
                AN15:
                  $ref: '#/components/schemas/Sensor'
                AN16:
                  $ref: '#/components/schemas/Sensor'
                AN17:
                  $ref: '#/components/schemas/Sensor'
                AN18:
                  $ref: '#/components/schemas/Sensor'
                AN19:
                  $ref: '#/components/schemas/Sensor'
                AN20:
                  $ref: '#/components/schemas/Sensor'
                AN21:
                  $ref: '#/components/schemas/Sensor'
                AN22:
                  $ref: '#/components/schemas/Sensor'
                AN23:
                  $ref: '#/components/schemas/Sensor'
                AN24:
                  $ref: '#/components/schemas/Sensor'
                AN25:
                  $ref: '#/components/schemas/Sensor'
                AN26:
                  $ref: '#/components/schemas/Sensor'
                AN27:
                  $ref: '#/components/schemas/Sensor'
                AN28:
                  $ref: '#/components/schemas/Sensor'
                AN29:
                  $ref: '#/components/schemas/Sensor'
                AN30:
                  $ref: '#/components/schemas/Sensor'
                AN31:
                  $ref: '#/components/schemas/Sensor'
                AN32:
                  $ref: '#/components/schemas/Sensor'
                DI1:
                  $ref: '#/components/schemas/Sensor'
                DI2:
                  $ref: '#/components/schemas/Sensor'
                DI3:
                  $ref: '#/components/schemas/Sensor'
                DI4:
                  $ref: '#/components/schemas/Sensor'
                DI5:
                  $ref: '#/components/schemas/Sensor'
                DI6:
                  $ref: '#/components/schemas/Sensor'
                DI7:
                  $ref: '#/components/schemas/Sensor'
                DI8:
                  $ref: '#/components/schemas/Sensor'
                DI9:
                  $ref: '#/components/schemas/Sensor'
                DI10:
                  $ref: '#/components/schemas/Sensor'
                DI11:
                  $ref: '#/components/schemas/Sensor'
                DI12:
                  $ref: '#/components/schemas/Sensor'
                DI13:
                  $ref: '#/components/schemas/Sensor'
                DI14:
                  $ref: '#/components/schemas/Sensor'
                DI15:
                  $ref: '#/components/schemas/Sensor'
                DI16:
                  $ref: '#/components/schemas/Sensor'
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
          description: ID of the user
        entityType:
          type: string
          format: string
          example: 'user'
          description: Entity type
        externalId:
          type: string
          format: string
          example: 'bruce.willis@gmail.com'
          description: User email
        entityStatus:
          type: string
          example: 'verified'
          description: The users account status within the Wingnut user portal (pending/verified)
        companyName:
          type: string
          example: 'Example Inc'
          description: The company the user is registered to
        config:
          type: object
          properties:
            firstName:
              type: string
              example: 'Bruce'
              description: The user's first name
            lastName:
              type: string
              example: 'Willis'
              description: The user's last name
            phone:
              type: string
              example: '+11231231234'
              description: The user's phone number
            email:
              type: string
              example: 'bruce.willis@gmail.com'
              description: The user's email address
            companyId:
              type: string
              example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
              description: The company Id the user is registered to
            role:
              type: string
              example: read
              description: The users permission role
    inline_response:
      required:
        - error
        - errorCode
      type: object
      properties:
        error:
          type: string
        errorCode:
          type: integer
    ListIdObjects:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
        description: Array of unique identifiers for entities
      example:
        - id: '05d8339f-3353-438a-9f90-470f6a175c8e'
        - id: '08ee2554-d9a7-4b6f-b79a-025100cc65c3'
    IdList:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
          description: Array of unique identifiers for entities
      example:
        ids:
          - '05d8339f-3353-438a-9f90-470f6a175c8e'
          - '08ee2554-d9a7-4b6f-b79a-025100cc65c3'
  parameters:
    X-Auth-Token:
      name: x-api-key
      in: header
      description: Authentication token
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
    UsersFetched:
      description: Successfully fetched account users IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListIdObjects'
    UsersQueried:
      description: Successfully queried detailed account users
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    WingnutsFetched:
      description: Successfully fetched account wingnut device IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListIdObjects'
    WingnutsQueried:
      description: Successfully queried detailed account wingnut devices
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Wingnut'
    PropertiesFetched:
      description: Successfully fetched account property IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListIdObjects'
    PropertiesQueried:
      description: Successfully queried detailed account properties
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Property'
    PropertyRecordsQueried:
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: string
                example: 'true'
                description: The query success or failure
              message:
                type: string
                example: 'There were 10 data points found'
                description: Success or failure message
              nextToken:
                type: string
                example: 'AYABeKYUDvlKolrlD5fm5lOEEXkAAAABAAdhd3Mta21zAEthcm46YXdzOmttczp1cy13ZXN0LTI6MzgzODMzNTc4NDA0OmtleS84ZjRlZDIxMi0wMzg5LTQ1OWYtYjQxZS02NmI4MTIxMjA2MmUAuAECAQB4_41BQXmUc7gPBqrt9bz_06cUCe3QMti9p6h9c77B-JIBzx_If9mcfb8QA0JxVQU0cwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJQY2LK4etUn_v9bygIBEIA7YbM14F-Wf-Qnl_OxSJlI5615hagU5oGy_W_ys6CWr475MmmeJjk6fV9XOfN09XRZbE5XnDgVjsbs0uACAAAAAAwAABAAAAAAAAAAAAAAAAAA7PJJaZKFvcT0mnwepWiyOv____8AAAABAAAAAAAAAAAAAAABAAABPw1NGW9p_fJmrmvYY9tr-z42DpA0P2STvSEtOwSmoyKgSjNvpCTDxE7i9KO99n8XcTT2TYVPTK0Q12oQ67DqfT3ye-D3bELAEVfSrtoQenuqCJ2Xy_4pxIfiXOimwvXcnLP6vD50zHv-035E92xAnUqfVKh3we08Ms8U_cnmazGG_ak5L2Krr44w--cja9heFOyIWOCUhdDTgZ4N5lLnD1fpEpyDqX2fwNuwtTSj6xSj5jwDy8dFgrvZjZ4gvFsg7B_NFRb9jMdMKVm9H33bvv7mdWZn-TKKXecyJOZcBNBPeex39TehyL92F-VpHjePP9CmzhfjYsrDiyeStSiLnMrY4S-wV-qznYq5Yzni-tJN2nKjF5E3F2Vvd1B186CKH36_7_cCSXtFGZphjGcsc2bljweniSfJ0b4N1hy2ks5YiRDKdUWwFYA3vvb4U4LZ'
                description: Only exists if there is more data than can fit in a single response to the original query. Use this token in the next subsequent query to contiue fetching data associated with the original query. If nextToken does not exist, there is no more data to be fetched and the query is complete.
              data:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: timestamp
                      example: '2024-08-17T15:29:15'
                      description: The timestamp of when the record was collected
                    propertyId:
                      type: string
                      example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
                      description: The property Id of where the record was collected
                    propertyExternalId:
                      type: string
                      example: '010203'
                      description: The user customizable property Id of where the record was collected
                    propertyName:
                      type: string
                      example: 'Bruces House'
                      description: The name of the property where the record was collected
                    boilerSystemPressure1:
                      type: string
                      example: '15.2'
                      description: an example data point for boiler system pressure 1. Any sensor/data label could be included in the record if exists and is included in the query body.
                    boilerSupplyHeaderTemperature1:
                      type: string
                      example: '166.123'
                      description: an example data point for boiler supply header temperature 1. Any sensor/data label could be included in the record if exists and is included in the query body.
                    boilerReturnHeaderTemperature1:
                      type: string
                      example: '156.542'
                      description: an example data point for boiler return header temperature 1. Any sensor/data label could be included in the record if exists and is included in the query body.
    PropertyRecords24Queried:
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: string
                example: 'true'
                description: The query success or failure
              message:
                type: string
                example: 'There were 10 data points found'
                description: Success or failure message
              nextToken:
                type: string
                example: 'AYABeKYUDvlKolrlD5fm5lOEEXkAAAABAAdhd3Mta21zAEthcm46YXdzOmttczp1cy13ZXN0LTI6MzgzODMzNTc4NDA0OmtleS84ZjRlZDIxMi0wMzg5LTQ1OWYtYjQxZS02NmI4MTIxMjA2MmUAuAECAQB4_41BQXmUc7gPBqrt9bz_06cUCe3QMti9p6h9c77B-JIBzx_If9mcfb8QA0JxVQU0cwAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJQY2LK4etUn_v9bygIBEIA7YbM14F-Wf-Qnl_OxSJlI5615hagU5oGy_W_ys6CWr475MmmeJjk6fV9XOfN09XRZbE5XnDgVjsbs0uACAAAAAAwAABAAAAAAAAAAAAAAAAAA7PJJaZKFvcT0mnwepWiyOv____8AAAABAAAAAAAAAAAAAAABAAABPw1NGW9p_fJmrmvYY9tr-z42DpA0P2STvSEtOwSmoyKgSjNvpCTDxE7i9KO99n8XcTT2TYVPTK0Q12oQ67DqfT3ye-D3bELAEVfSrtoQenuqCJ2Xy_4pxIfiXOimwvXcnLP6vD50zHv-035E92xAnUqfVKh3we08Ms8U_cnmazGG_ak5L2Krr44w--cja9heFOyIWOCUhdDTgZ4N5lLnD1fpEpyDqX2fwNuwtTSj6xSj5jwDy8dFgrvZjZ4gvFsg7B_NFRb9jMdMKVm9H33bvv7mdWZn-TKKXecyJOZcBNBPeex39TehyL92F-VpHjePP9CmzhfjYsrDiyeStSiLnMrY4S-wV-qznYq5Yzni-tJN2nKjF5E3F2Vvd1B186CKH36_7_cCSXtFGZphjGcsc2bljweniSfJ0b4N1hy2ks5YiRDKdUWwFYA3vvb4U4LZ'
                description: Only exists if there is more data than can fit in a single response to the original query. Use this token in the next subsequent query to contiue fetching data associated with the original query. If nextToken does not exist, there is no more data to be fetched and the query is complete.
              data:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: timestamp
                      description: The timestamp of when the record was collected
                    propertyId:
                      type: string
                      description: The property Id of where the record was collected
                    propertyExternalId:
                      type: string
                      description: The user customizable property Id of where the record was collected
                    propertyName:
                      type: string
                      description: The name of the property where the record was collected
                    boilerSystemPressure1:
                      type: string
                      description: an example data point for boiler system pressure 1. Any sensor/data label could be included in the record if exists and is included in the query body.
                    boilerSupplyHeaderTemperature1:
                      type: string
                      description: an example data point for boiler supply header temperature 1. Any sensor/data label could be included in the record if exists and is included in the query body.
                    boilerReturnHeaderTemperature1:
                      type: string
                      description: an example data point for boiler return header temperature 1. Any sensor/data label could be included in the record if exists and is included in the query body.
                example:
                  - time: '2024-08-17T15:29:15'
                    propertyId: '12345678-90ab-cdef-1234-567890abcdef'
                    propertyExternalId: '010203'
                    propertyName: 'Bruces House'
                    boilerSystemPressure1: '15.2'
                    boilerSupplyHeaderTemperature1: '166.123'
                    boilerReturnHeaderTemperature1: '156.542'
                  - time: '2024-08-17T15:29:15'
                    propertyId: '22345678-90ab-cdef-1234-567890abcdef'
                    propertyExternalId: '111213'
                    propertyName: 'Bruces Second House'
                    boilerSystemPressure1: '13.2'
                    boilerSupplyHeaderTemperature1: '145.321'
                    boilerReturnHeaderTemperature1: '132.987'
                description: An array of records objects, each object containing sensor records values that were requested in the query. Properties requested will have sepearte records across all objects returned.
    NoContent:
      description: Request success - No data points found
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response'
          example:
            value:
              error: 'There was a server issue'
              errorCode: 400
    Forbidden:
      description: Invalid authentication or insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response'
          example:
            value:
              error: 'Forbidden'
              errorCode: 403
    ResourceNotFound:
      description: Cannot find request resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response'
          example:
            value:
              error: 'Unsupported route: GET /example'
              errorCode: 404
  requestBodies:
    QueryEntities:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdList'
      required: true
    QueryPropertyRecords24H:
      content:
        application/json:
          schema:
            type: object
            properties:
              start_timestamp:
                type: string
                format: timestamp
                example: '2024-08-17T15:29:15'
                description: The time by which to start querying records for in format yyyy-MM-ddTHH:mm:ss
              end_timestamp:
                type: string
                format: timestamp
                example: '2024-08-17T15:29:15'
                description: The time by which to stop querying records for in format yyyy-MM-ddTHH:mm:ss
              properties:
                type: array
                items:
                  type: string
                example:
                 - '12345678-90ab-cdef-1234-567890abcdef'
                 - '22345678-90ab-cdef-1234-567890abcdef'
                description: Array of properties to query records for
              labels:
                type: array
                items:
                  type: string
                example:
                  - 'BoilerSystemPressure1'
                  - 'BoilerSupplyHeaderTemperature1'
                  - 'BoilerReturnHeaderTemperature1'
                description: An array of sensor/data labels to query records for
              next_token:
                type: string
                format: uuid
                example: '12345678-90ab-cdef-1234-567890abcdef'
                description: Returns the next subsequent page of results from a prior query. Must be included as empty string if no prior query.
            required:
              - start_timestamp
              - end_timestamp
              - labels
              - properties
              - next_token
    QueryPropertyRecords:
      content:
        application/json:
          schema:
            type: object
            properties:
              start_timestamp:
                type: string
                format: timestamp
                example: '2024-08-17T15:29:15'
                description: The time by which to start querying records for in format yyyy-MM-ddTHH:mm:ss
              end_timestamp:
                type: string
                format: timestamp
                example: '2024-08-17T15:29:15'
                description: The time by which to stop querying records for in format yyyy-MM-ddTHH:mm:ss
              property:
                type: string
                format: uuid
                example: '12345678-90ab-cdef-1234-567890abcdef'
              labels:
                type: array
                items:
                  type: string
                example:
                  - 'BoilerSystemPressure1'
                  - 'BoilerSupplyHeaderTemperature1'
                  - 'BoilerReturnHeaderTemperature1'
                description: An array of desired sensor/data labels to be queried
              next_token:
                type: string
                format: uuid
                example: '12345678-90ab-cdef-1234-567890abcdef'
                description: Returns the next subsequent page of results from a prior query. Must be included as empty string if no prior query.
            required:
              - start_timestamp
              - end_timestamp
              - labels
              - properties
              - next_token
